Repository altiscope/throwaway-poc-bill-nye, pull requests merged in 2020-04, with the labels that each got.

#27 25
  file
Labels: major

#28 26
  file
Labels: major

#29 27
  file
Labels: major

#30 28
  file
Labels: major

#31 29
  file
Labels: major

#33 31
  file
Labels: major

#34 32
  file
Labels: patch

#35 33
  file
Labels: patch

#36 34
  file
Labels: major

#37 35
  file
Labels: major

#38 Adding a git config list debug.
  .github/workflows/release.yml
Labels: patch

#39 Update file
  file
Labels: patch

#40 Update file
  file
Labels: patch

#41 Update file
  file
Labels: patch

#42 Update file
  file
Labels: patch

#43 Update file
  file
Labels: patch

#44 Update file
  file
Labels: patch

#45 Update release.yml
  .github/workflows/release.yml
Labels: patch

#46 minor
  file
Labels: minor

#47 Update file
  file
Labels: minor

#48 xxx
  file
Labels: minor

#49 Update file
  file
Labels: minor

#50 Update file
  file
Labels: major

#55 R
  file
Labels: major
